version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/usr/share/nginx/html:ro
      # Uncomment and update paths for SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
